[package]
name = "ptc-mod"
description = "Mod for ptCollage"
version = "0.2.0"
repository = "https://github.com/PieKing1215/ptcMod"
authors = ["PieKing1215"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2024"
build = "src/build.rs"

[dependencies]
process-memory = "0.5"
sysinfo = { version = "0.39", default-features = false, features = ["system"] }
windows = { version = "0.62", features = ["Win32_System_Console", "Win32_System_LibraryLoader", "Win32_Storage_FileSystem", "Win32_UI_WindowsAndMessaging", "Win32_System_SystemServices", "Win32_System_Threading", "Win32_Security", "Win32_System_Memory", "Win32_System_Diagnostics_Debug", "Win32_Graphics_DirectDraw", "Win32_Graphics_Gdi", "Win32_System_Ole", "Win32_System_Com", "Win32_System_Com_StructuredStorage"] }
windows-core = "0.62"
libc = { version = "0.2", features = ["use_std", "extra_traits"] }
log = "0.4"
simplelog = "0.12"
anyhow = "1.0"
colorsys = "0.7"
path-absolutize = "4.0" # so we can get absolute paths to missing files
lazy_static = "1.4"
regex = "1.5"
# using the default "rustls" pulls in aws-lc-sys which causes build issues on my setup, and going back to native-tls causes sporadic response reading timeouts
# so need to install ring provider manually
reqwest = { version = "0.13", default-features = false, features = ["blocking", "rustls-no-provider"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
widestring = "1.2"
static_assertions = "1.1.0"

[lib]
name = "ptc_mod"
crate-type = ["cdylib"] # dll
