name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        rustup target add i686-pc-windows-gnu
        rustup toolchain install stable-i686-pc-windows-gnu
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release --verbose
    - name: Zip
      run: zip -j ptcMod.zip target/i686-pc-windows-gnu/debug/ptc-mod.exe target/i686-pc-windows-gnu/debug/ptc_mod.dll
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: ptcMod.zip
